### ISSUE TITLE
Can QiLin use one specified method as the entry for pointer analysis?

### ISSUE THREAD

**Issue by Tangben1997** [QilinPTA/Qilin#2]
I want to specify a method (not main()) as the entry for PTA. What part of the code do I need to modify to do this?

**Comment by DongjieHe** [comment]
Hi, I suggest you to refer to "qilin.core.builder.FakeMainFactory:getEntryPoints()". 
You can specify whatever methods as the entries by rewriting the `getEntryPoints()` method.
