### ISSUE TITLE
-pta   ko、kc and so on UNSUPPORT

### ISSUE THREAD

**Issue by dyd1024** [QilinPTA/Qilin#3]
When I run Qilin as following:
java -cp /home/monadic/java_project/Qilin/artifact/Qilin-1.0-SNAPSHOT.jar driver.Main -pae -pe -clinit=ONFLY -lcs -mh -pta=ko -apppath /home/monadic/java_project/Qilin/docs/example/example01/example.jar -mainclass Main -jre=/home/monadic/java_project/Qilin/artifact/benchmarks/JREs/jre1.8.0_312/ -se -jimple

I have encountered the following error:
[main] ERROR driver.PTAOption - Error parsing command line options
java.lang.RuntimeException: Unsupported PTA: ko !
	at driver.PTAPattern.parsePTACommand(PTAPattern.java:51)
	at driver.PTAPattern.<init>(PTAPattern.java:35)
	at driver.PTAOption.parseCommandLineOptions(PTAOption.java:116)
	at driver.PTAOption.parseCommandLine(PTAOption.java:98)
	at driver.Main.run(Main.java:41)
	at driver.Main.mainRun(Main.java:58)
	at driver.Main.main(Main.java:172)

How can I do to make Qilin support ko/kc and so on? Thank you.

**Comment by DongjieHe** [comment]
Hi, `ko` and `kc` represent k-object-sensitive pointer analysis and k-callsite-sensitive pointer analysis respectively. When using Qilin, please specify a specific small constant like `1` or `2` to replace the symbol `k`.

**Comment by DongjieHe** [comment]
Just try the below command:
```bash
java -cp /home/monadic/java_project/Qilin/artifact/Qilin-1.0-SNAPSHOT.jar driver.Main -pae -pe -clinit=ONFLY -lcs -mh -pta=1o -apppath /home/monadic/java_project/Qilin/docs/example/example01/example.jar -mainclass Main -jre=/home/monadic/java_project/Qilin/artifact/benchmarks/JREs/jre1.8.0_312/ -se -jimple
```

**Comment by dyd1024** [comment]
thank you☺️



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月28日 15:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [QilinPTA/Qilin] -pta   ko、kc and so on UNSUPPORT (Issue #3) |

Just try the below command:

java -cp /home/monadic/java_project/Qilin/artifact/Qilin-1.0-SNAPSHOT.jar driver.Main -pae -pe -clinit=ONFLY -lcs -mh -pta=1o -apppath /home/monadic/java_project/Qilin/docs/example/example01/example.jar -mainclass Main -jre=/home/monadic/java_project/Qilin/artifact/benchmarks/JREs/jre1.8.0_312/ -se -jimple
