### ISSUE TITLE
Running Code in a Single Thread

### ISSUE THREAD

**Issue by ysarita2** [QilinPTA/Qilin#4]
Hi there,

Thanks for creating this high performance implementation of the pointer analysis in Java, I find it very easy to install, run, and produce results for my work. I have noticed that your code always runs with multiple threads and I was wondering if it is possible to run it on one thread. 

Regards,
Yasmin

**Comment by DongjieHe** [comment]
Hi, 
Our solver actually runs in a single thread. We are trying to make the solver run with multiple threads but due to performance reasons, we have not submitted the code to the master branch.
