### ISSUE TITLE
no problems

### ISSUE THREAD

**Issue by Yanllan** [QilinPTA/Qilin#7]
Hello! It's nice to see that you did this model, but I don't seem to see any benchmark results in your paper? So have you done it yet? Especially the conclusions of VQA-RAD and PATH-VQA?

**Comment by DongjieHe** [comment]
Hi, we have some benchmark results in Tables 5 and 7 of the paper. I don't remember that we have `VQA-RAD` and `PATH-VQA` in our paper. You can reproduce the results in our paper via the [artifact](https://drops.dagstuhl.de/entities/document/10.4230/DARTS.8.2.6)

**Comment by Yanllan** [comment]
I'm really sorry! 
There is a project with the same name I made a mistake, sorry to bother you!
