### ISSUE TITLE
How to create and run a new pointer analysis with an existing Soot Scene?

### ISSUE THREAD

**Issue by MoonBirdLin** [QilinPTA/Qilin#8]
Hi, thanks for your excellent work.

I am currently working on implementing a custom pointer analysis for APK files. However, I have encountered a few issues.

First, before running the new pointer analysis, I need to perform some additional analysis to infer and exclude third-party sdks, and I am using a set of entry points that I have computed myself. Therefore, I need to parse the APK’s code and apk resources with Soot and FlowDroid. As a result, I cannot directly use Qilin command or setup Qilin with `driver.Main.setupSoot()` and then run PTA with `Pta.run()`. Could you please advise on how I should setup and run Qilin with modified Soot Scene Instance? (B.T.W, I use Soot-4.5.0.)

Second, since my custom pointer analysis design includes some custom allocation points (for example, I treat calls to `Context.getIntent()` as allocateNodes) and pointer propagation calculations (`Intent.setXXXParcelable()` will be seen as special pointer propagation edges), I may need to define and implement a new `Propagator`. Is it possible to implement such a custom pointer analysis using Qilin? If so, which classes and methods would I need to override?

Thank you again for your outstanding work. I'm looking forward to your response.

**Comment by DongjieHe** [comment]
Hi, 
Let us first discuss your first question.
In "public static PTA run(String[] args)" of class Main (pased below for your convenience), "`setupSoot()`" is to load classes and methods into the scene. Since you are parsing APK's code and already have your entry points, logically, you do not need to do this step anymore.

``` java
public static PTA run(String[] args) {
    PTA pta;
    new PTAOption().parseCommandLine(args);
    setupSoot();
    if (PTAConfig.v().getOutConfig().dumpJimple) {
        String jimplePath = PTAConfig.v().getAppConfig().APP_PATH.replace(".jar", "");
        PTAUtils.dumpJimple(jimplePath);
        System.out.println("Jimple files have been dumped to: " + jimplePath);
    }
    pta = PTAFactory.createPTA(PTAConfig.v().getPtaConfig().ptaPattern);
    pta.run();
    return pta;
}
```

`pta.run()` starts the points-to analysis, which will execute into `public void propagate()` in class `Solver`, where `cgb.initReachableMethods();` will initialise the entry points in normal Java code. You can modify the `public List<MethodOrMethodContext> getEntryPoints()` method to support your customised entry points or insert call instructions to the entry points in the FakeMainMethod.

**Comment by DongjieHe** [comment]
As for the custom allocation points, you can modify the class `MethodNodeFactory`. Currently, we create abstract objects for `new` and `new Array` expressions:
```java
    private AllocNode caseNewArrayExpr(NewArrayExpr nae) {
        return pag.makeAllocNode(nae, nae.getType(), method);
    }

    private AllocNode caseNewExpr(NewExpr ne) {
        SootClass cl = PTAScene.v().loadClassAndSupport(ne.getType().toString());
        PTAUtils.clinitsOf(cl).forEach(mpag::addTriggeredClinit);
        return pag.makeAllocNode(ne, ne.getType(), method);
    }
```
you can add your modifications in `protected void handleInvokeStmt(Stmt s)`. When the statement matches your custom calls, e.g., "Context.getIntent()", you can introduce a unique abstract object for that callsite.

**Comment by DongjieHe** [comment]
As for your last question, i.e., "pointer propagation calculations (modeling Intent.setXXXParcelable() as special pointer propagation edges)", I do not think you need to rewrite a `Propagator`.  You only need to model it as an edge when constructing the methodPAG. In orther words, I think you only need to modify `protected void handleInvokeStmt(Stmt s)` and when encountering the call statement of "Intent.setXXXParcelable() ", you should try to invoke `mpag.addInternalEdge(src, dest);` somewhere in the method. 

Any questions, welcome to further discussion.

**Comment by MoonBirdLin** [comment]
Helpful explanation! I’ll try your suggestions.
Thanks for your distinguished work again! (^_^)
